#ifndef BSP_H
#define BSP_H



#define ON_FLOTTOR_ACTIVATED 1
#define ON_FLOTTOR_DESACTIVATED 0


#define BUTTON_IS_PRESSED 1
#define BUTTON_IS_RELEASED 0

#define BUZZER_ACTIVATED 1
#define BUZZER_DESACTIVATED 0
#define ACTIVATE_BUZZER 1
#define DESACTIVATE_BUZZER 0


#define ON_FLOTTOR_ACTIVATED 1
#define ON_FLOTTOR_DESACTIVATED 0


#define LED_IS_TURNED_ON 1
#define LED_IS_TURNED_OFF 0
#define TURN_ON_LED 1
#define TURN_OFF_LED 0

#define BUZZER_IS_TURNED_ON 1
#define BUZZER_IS_TURNED_OFF 0
#define TURN_ON_BUZZER 1
#define TURN_OFF_BUZZER 0

#define ON_GENERIC_RELAY_OPENED 0
#define ON_GENERIC_RELAY_CLOSED 1
#define OPEN_GENERIC_RELAY 0
#define CLOSE_GENERIC_RELAY 1



#define ON_RELAY_BATTERY_POWER_SUPPLY_OPENED ON_GENERIC_RELAY_OPENED
#define ON_RELAY_BATTERY_POWER_SUPPLY_CLOSED ON_GENERIC_RELAY_CLOSED
#define OPEN_RELAY_BATTERY_POWER_SUPPLY OPEN_GENERIC_RELAY
#define CLOSE_RELAY_BATTERY_POWER_SUPPLY CLOSE_GENERIC_RELAY


#define ON_RELAY_MOTOR_GROUP_OPENED ON_GENERIC_RELAY_OPENED
#define ON_RELAY_MOTOR_GROUP_CLOSED ON_GENERIC_RELAY_CLOSED
#define OPEN_RELAY_MOTOR_GROUP OPEN_GENERIC_RELAY
#define CLOSE_RELAY_MOTOR_GROUP CLOSE_GENERIC_RELAY
#define TEMPERATURE_CONDITION 3 
#define BATTERY_LEVEL_CONDITION 2
#define RESERVE_LEVEL_CONDITION 1
#define STEG_ELECTRICITY_CONDITION 0



#define ON_RELAY_PUMP_CLOSED 1
#define ON_RELAY_PUMP_OPENED 0

#define ON_BATTERY_CHARGED FLOTTOR_IS_DESACTIVATED
#define ON_BATTERY_LOW FLOTTOR_IS_DESACTIVATED
#define MIN_VOLTAGE_VALUE 11.5
#define ON_VOLTAGE_SENSOR_HIGH true
#define ON_VOLTAGE_SENSOR_LOW false
#define ON_BATTERY_LEVEL_CHARGED ON_VOLTAGE_SENSOR_HIGH
#define ON_BATTERY_LEVEL_LOW ON_VOLTAGE_SENSOR_LOW
#define TURN_ON_BATTERY_POWER_SUPPLY CLOSE_RELAY_BATTERY_POWER_SUPPLY
#define CUT_OFF_BATTERY_POWER_SUPPLY OPEN_RELAY_BATTERY_POWER_SUPPLY


#define TURN_ON_PUMP ON_RELAY_PUMP_CLOSED
#define TURN_OFF_PUMP ON_RELAY_PUMP_OPENED
#define ON_RESERVE_FILLED ON_FLOTTOR_DESACTIVATED 
#define ON_RESERVE_EMPTIED ON_FLOTTOR_ACTIVATED 


#define TEMPERATURE_DANGER_VALUE 90.0
#define ON_TEMP_SENSOR_HIGH true
#define ON_TEMP_SENSOR_LOW false
#define ON_SYSTEM_TEMPERATURE_IN_DANGER_VALUE ON_TEMP_SENSOR_HIGH
#define ON_SYSTEM_TEMPERATURE_IN_SECURE_VALUE ON_TEMP_SENSOR_LOW
#define TURN_ON_MOTOR_GROUP CLOSE_RELAY_MOTOR_GROUP
#define TURN_OFF_MOTOR_GROUP OPEN_RELAY_MOTOR_GROUP

#define ON_TEST_BUTTON_CLICKED 1
#define ON_TEST_BUTTON_RELEASED 0

#define ON_RESET_ALERT_BUTTON_CLICKED 1
#define ON_RESET_ALERT_BUTTON_RELEASED 0

#define ON_STEG_ELECTRICITY_WORKING 1
#define ON_STEG_ELECTRICITY_CUTTED 0


#define ON_BUTTON_AUTO_MODE_SELECTED 1
#define ON_BUTTON_MAN_MODE_SELECTED 0

#define ON_AUTO_MODE_SELECTED ON_BUTTON_AUTO_MODE_SELECTED
#define ON_MAN_MODE_SELECTED ON_BUTTON_MAN_MODE_SELECTED
#define DISPLAY_MODE_AUTO 1
#define DISPLAY_MODE_MAN 0

//pins
 //output pins
#define pumpRelayPin 5
#define motorGroupRelayPin 6
#define batteryPowerSupplyRelayPin 7
#define buzzerAlertPin 8
#define ledAlertPin 2

 //input pins
#define flottorPin 4
#define buttonAutoManPin 3
#define testMotorGroupButtonPin (int)A3
#define resetAlertButtonPin 9
#define pt100Pin (int)A0
#define stegContactorPin (int)A2
#define voltageSensorPin (int)A1

#define baud_rate 9600



#endif